/Users/rohanmehta/anaconda3/envs/jax/lib/python3.11/site-packages/haliax/nn/__init__.py:159: UserWarning: target_y has dtype uint8, which is not a floating point type. This is probably a mistake.
  warnings.warn(
[34m[1mwandb[39m[22m: Network error resolved after 0:00:34.056952, resuming normal operation.
Step: 0 | Average Train Loss: 200634496.00 | Average Val Loss: 195769936.00
Traceback (most recent call last):
  File "/Users/rohanmehta/Desktop/ML Projects/GPT_nano/train.py", line 394, in <module>
    main()
  File "/Users/rohanmehta/anaconda3/envs/jax/lib/python3.11/site-packages/draccus/argparsing.py", line 182, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohanmehta/Desktop/ML Projects/GPT_nano/train.py", line 391, in main
    trainer.train()
  File "/Users/rohanmehta/Desktop/ML Projects/GPT_nano/train.py", line 343, in train
    if val_loss < self.best_val_loss or self.trainer_config.always_save_checkpoint:
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainerConfig' object has no attribute 'always_save_checkpoint'
Traceback (most recent call last):
  File "/Users/rohanmehta/Desktop/ML Projects/GPT_nano/train.py", line 394, in <module>
    main()
  File "/Users/rohanmehta/anaconda3/envs/jax/lib/python3.11/site-packages/draccus/argparsing.py", line 182, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohanmehta/Desktop/ML Projects/GPT_nano/train.py", line 391, in main
    trainer.train()
  File "/Users/rohanmehta/Desktop/ML Projects/GPT_nano/train.py", line 343, in train
    if val_loss < self.best_val_loss or self.trainer_config.always_save_checkpoint:
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainerConfig' object has no attribute 'always_save_checkpoint'. Did you mean: 'always_save_ckpt'?